apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "thomasmoraes02/hello-go:v5.6"
        
        startupProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 30
          
        # Sem mandar tráfego para a aplicação
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 1
          initialDelaySeconds: 10

        # Faz uma requisição interna para o container
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
          initialDelaySeconds: 15

        # Recursos
        resources:
          # O minimo que a aplicação precisa para rodar
          # Estamos reservando esses recursos do nosso cluster para esse POD
          requests:
            # Unidade de medida de CPU: vCPU -> 1000m (milicores) 
            cpu: "0.05"
            memory: "20Mi"
          
          # Até onde o POD pode usar de recursos do nosso cluster
          limits:
            cpu: "0.05"
            memory: "25Mi"

        volumeMounts:
          - mountPath: "/go/myfamily"
            name: config
            readOnly: true
          - mountPath: "/go/pvc"
            name: goserver-volume

        envFrom:
          - configMapRef:
              name: goserver-env

        # Alternativas
        # env:
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: NAME

        #   # tem esse caminho
        #   - name: AGE
        #     value: "26"
        ports:
        - containerPort: 8080

      volumes:
        - name: config
          configMap:
            name: configmap-family
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc
