apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "thomasmoraes02/hello-go:v5.5"
        
        startupProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 30
          
        # Sem mandar tráfego para a aplicação
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 1
          initialDelaySeconds: 10

        # Faz uma requisição interna para o container
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
          initialDelaySeconds: 15

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

            
        envFrom:
          - configMapRef:
              name: goserver-env

        # Alternativas
        # env:
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: NAME

        #   # tem esse caminho
        #   - name: AGE
        #     value: "26"
        ports:
        - containerPort: 8080
